### ISSUE TITLE
Incompatible with switch from SIGNPOST to INDEX_CLIENT in version 1.1.12 of sheepdog

### ISSUE THREAD

**Issue by pschumm** [uc-cdis/compose-services#46]
This prevents sheepdog from starting when launched with compose-services. At a minimum, `templates/sheepdog_settings.py` and `templates/peregrine_settings.py` would have to be modified, I think (i.e., change `SIGNPOST` to `INDEX_CLIENT` and `SIGNPOST_HOST` to `INDEX_CLIENT_HOST`), and perhaps other updates will be required as well?

**Comment by paulineribeyre** [comment]
Hello, this should be fixed now. You will need to re-run `creds_setup.sh` to update the peregrine and sheepdog config. Thank you for drawing our attention to this!
